name: travelplanner
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.3 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  splashscreen: ^1.3.5
  carousel_slider: any
  google_fonts: ^2.1.0
  font_awesome_flutter: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets:
  - C:/Users/JUDICAEL-FLORENT/Desktop/COURS 3IL/TravelP/TravelPlanner/images/travelo.png
  - C:/Users/JUDICAEL-FLORENT/Desktop/COURS 3IL/TravelP/TravelPlanner/images/labelacceuil.jpg
  - C:/Users/JUDICAEL-FLORENT/Desktop/COURS 3IL/TravelP/TravelPlanner/images/back.png
